/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jamaludin Septian
 */
public class oderDetail extends javax.swing.JFrame {
    private Connection con = new koneksi().connect();
    private Statement stat;
    private ResultSet res;
    private DefaultTableModel tabmode;
    /**
     * Creates new form oderDetail
     */
    public oderDetail() {
        initComponents();
        datatable();
        idSuratJalan();
        idBarang();
    }
    protected void kosong() {
        tJumlah.setText("");
        tIdDetail.setText("");
    }
    
    protected void datatable() {
        Object[] Baris={"ID Detail","ID Surat Jalan","ID Barang","Jumlah"};
        tabmode=new DefaultTableModel(null,Baris);
        tableOrderDetail.setModel(tabmode);
        String sql="SELECT * FROM deliveryorderdetail";
        
        try{
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_detail");
                String b = hasil.getString("id_surat_jalan");
                String c = hasil.getString("id_barang");
                String d = hasil.getString("jumlah");
              
                String[] data={a,b,c,d};
                tabmode.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    
    private void idSuratJalan(){
        String sql = "SELECT * FROM deliveryorder";
        try {
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                jIdSuratJalan.addItem(hasil.getString(1));
            }
        } catch (SQLException ex) {
            
        }
    }
    private void idBarang(){
        String sql = "SELECT * FROM items";
        try {
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            jIdBarang.removeAll();
            while(hasil.next()){
                jIdBarang.addItem(hasil.getString(1));
            }
        } catch (SQLException ex) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        ID_BARANG = new javax.swing.JLabel();
        Penerima = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderDetail = new javax.swing.JTable();
        jIdSuratJalan = new javax.swing.JComboBox<>();
        jIdBarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tIdDetail = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        Penerima1 = new javax.swing.JLabel();
        tNamaBarang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID_Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 99, 45));

        bSimpan.setBackground(new java.awt.Color(102, 204, 255));
        bSimpan.setForeground(new java.awt.Color(51, 51, 51));
        bSimpan.setText("SAVE");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 260, 50));

        ID_BARANG.setText("ID_Barang");
        getContentPane().add(ID_BARANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 109, 99, 45));

        Penerima.setText("Nama Barang");
        getContentPane().add(Penerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 99, 45));

        tJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(tJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, 45));

        tableOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableOrderDetail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 850, 100));

        getContentPane().add(jIdSuratJalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 211, 38));

        jIdBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jIdBarangItemStateChanged(evt);
            }
        });
        jIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdBarangActionPerformed(evt);
            }
        });
        getContentPane().add(jIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 211, 38));

        jLabel2.setText("ID_Surat Jalan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, 45));

        tIdDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdDetailActionPerformed(evt);
            }
        });
        getContentPane().add(tIdDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 210, 45));

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cetak.png"))); // NOI18N
        btnCetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        Penerima1.setText("Jumlah");
        getContentPane().add(Penerima1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 172, 99, 45));

        tNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String idsuratjalan = jIdSuratJalan.getSelectedItem().toString();
        String idbarang = jIdBarang.getSelectedItem().toString();
        String sql = "INSERT INTO deliveryorderdetail values(?,?,?,?)";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, tIdDetail.getText());
            stat.setString(2, idsuratjalan);
            stat.setString(3, idbarang);
            stat.setString(4, tJumlah.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan");
            kosong();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Simpan"+e);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJumlahActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tJumlahActionPerformed

    private void tIdDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdDetailActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
        String path = "C:\\Users\\Jamaludin Septian\\Documents\\NetBeansProjects\\aplikasi_kkp\\src\\cetakan\\report_order.jasper";

        try {
            HashMap hash = new HashMap();
            String inputId = JOptionPane.showInputDialog("Masukkan Id Surat Jalan:");
            hash.put("id_surat_jalan", inputId);

            reports = (JasperReport) net.sf.jasperreports.engine.util.JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, hash, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
           
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jIdBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jIdBarangItemStateChanged
        // TODO add your handling code here:
       
       String sql = "SELECT nama_barang FROM items where id_barang = ? ";
        try {
            java.sql.Statement stat=con.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while(hasil.next()){
                 tNamaBarang.setText(hasil.getString("nama_barang"));
            }
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_jIdBarangItemStateChanged

    private void jIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdBarangActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jIdBarangActionPerformed

    private void tNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_BARANG;
    private javax.swing.JLabel Penerima;
    private javax.swing.JLabel Penerima1;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton btnCetak;
    private javax.swing.JComboBox<String> jIdBarang;
    private javax.swing.JComboBox<String> jIdSuratJalan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tIdDetail;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNamaBarang;
    private javax.swing.JTable tableOrderDetail;
    // End of variables declaration//GEN-END:variables
}
